---
- include_role:
    name: apt-installer
  vars:
    package: "{{ item }}"
  loop:
    - snap
    - snapd

- name: enable snapd service
  systemd:
    name: snapd
    state: started
    enabled: yes
  become: yes
  changed_when: false

- name: minimal retain previous versions
  shell: snap set system refresh.retain=2
  become: yes
  changed_when: false
