---
- include_role:
    name: apt-installer
  vars:
    package: "{{ item }}"
  loop:
    - python3
    - python3-pip
#    - python3-dev

- name: set python3 as default
  shell: update-alternatives --install /usr/bin/python python /usr/bin/python3 1
  become: true
  changed_when: false

- name: show python version
  shell: python3 --version
  changed_when: false
