---
- name: create default user
  ansible.builtin.user:
    name: user
    shell: /bin/bash
    groups: sudo
    append: yes
    generate_ssh_key: no
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
  become: yes
  changed_when: false

- name: fetch ssh keys from remote server
  fetch:
    src: ".ssh/{{ item }}"
    dest: "."
  become_user: user
#  become: yes
  loop:
    - id_rsa
    - id_rsa.pub
  changed_when: false