---
- block:
    - include_role:
        name: apt-installer

  rescue:
    - name: keepassxc
      snap:
        name: keepassxc
        state: present
        channel: latest/stable
      become: yes
      changed_when: false
