---
- name: Update cache
  apt: update_cache=yes
  become: yes
  changed_when: false

- name: Install Missing Packages
  shell: apt install -f -y
  register: shell
  changed_when: false
  become: yes

- name: GUI
  block:
    - include_role: name=default-gui
    - include_role: name=default-shell
    - import_tasks: tasks/grub.yml
  when: GUI or DESKTOP

- name: KEEPASS
  block:
    - include_role: name=keepassxc
  when: KEEPASS or DESKTOP

- name: CHROME
  block:
    - include_role: name=chrome

    #  - name: Brave
    #    shell: snap install brave
    #    args:
    #      executable: /bin/bash
    #
    #  - name: Brave beta
    #    shell: |
    #      curl https://s3-us-west-2.amazonaws.com/brave-apt-staging/keys.asc | apt-key add -
    #      echo "deb [arch=amd64] https://s3-us-west-2.amazonaws.com/brave-apt-staging `lsb_release -sc` main" | tee /etc/apt/sources.list.d/brave-`lsb_release -sc`.list
    #      apt update
    #      apt install -y brave-beta
    #    args:
    #      executable: /bin/bash

  when: CHROME or DESKTOP

- name: CODING
  block:
    - include_role: name=git
    - include_role: name=pycharm
    - include_role: name=tmux
    - include_role: name=vim
    - include_role: name=neovim
    - include_role: name=curl
    - include_role: name=rsync
    - include_role: name=python3

#    - name: Atom
#      apt:
#        deb: https://atom-installer.github.com/v1.38.2/atom-amd64.deb?s=1560782772&ext=.deb
#      ignore_errors: yes
#      become: yes
#      changed_when: false
#
#    - name: Visual Studio Code
#      snap:
#        name: code-insiders
#        classic: yes
#        state: present
#      become: yes
#      changed_when: false

#    - name: Sublime 3
#      shell: |
#        wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -
#        apt-get install -y apt-transport-https
#        echo "deb https://download.sublimetext.com/ apt/stable/" | tee /etc/apt/sources.list.d/sublime-text.list
#      become: yes
#      changed_when: false
#      args:
#        executable: /bin/bash
#    - include_role:
#        name: apt-installer
#        vars:
#          package: sublime-text

  when: CODING or DESKTOP

- name: PHOTOGRAPHY
  block:
    - include_role: name=darktable
  when: PHOTOGRAPHY or DESKTOP

- name: MEDIA
  block:
    - include_role: name=kdenlive
    - include_role: name=gimp
    - include_role: name=audacity
  when: MEDIA or DESKTOP

- name: GAMING
  block:
    # - name: PlayOnLinux
    #   apt:
    #     deb: https://www.playonlinux.com/script_files/PlayOnLinux/4.2.12/PlayOnLinux_4.2.12.deb
    #   ignore_errors: yes
    # - name: PlayOnLinux
    #   shell: |
    #     apt install -f -y
    #     dpkg --add-architecture i386
    # - name: PlayOnLinux - wine
    #   apt: update_cache=yes name=wine-development state=present
    # - name: PlayOnLinux - winbind
    #   apt: update_cache=no name=winbind state=present
    # - name: PlayOnLinux - update missing packages
    #   shell: apt install -f -y

    - name: Lutris - repo
      apt_repository: repo='ppa:lutris-team/lutris'
      become: yes
      changed_when: false
    - name: Lutris
      apt: update_cache=yes name=lutris state=latest
      become: yes
      changed_when: false

    - name: Wine i386 architecture
      shell: dpkg --add-architecture i386
      become: yes
      changed_when: false
    - name: Wine apt key
      apt_key:
        url: https://dl.winehq.org/wine-builds/winehq.key
        state: present
      become: yes
      changed_when: false
    - name: Wine repo
      apt_repository:
        repo: deb https://dl.winehq.org/wine-builds/ubuntu/ focal main
        state: present
      become: yes
      changed_when: false
    - include_role:
        name: apt-installer
      vars:
        package: wine32
    - include_role:
        name: apt-installer
      vars:
        package: wine64
    - name: Wine staging
      apt:
        name: winehq-staging
        state: latest
        install_recommends: yes
        update_cache: yes
      become: yes
      changed_when: false
    - include_role:
        name: apt-installer
      vars:
        package: fonts-wine

  when: GAMING or DESKTOP


- name: everything else
  block:

    - include_role: name=gcc
    - include_role: name=pass
    - include_role: name=rclone
    - include_role: name=nemo
    - include_role: name=docker

    - include_role:
        name: apt-installer
      vars:
        package: software-properties-common

    - include_role:
        name: apt-installer
      vars:
        package: sudo

    - include_role:
        name: apt-installer
      vars:
        package: make

    - include_role:
        name: apt-installer
      vars:
        package: perl

    - include_role:
        name: apt-installer
      vars:
        package: unzip

    - include_role:
        name: apt-installer
      vars:
        package: chrome-gnome-shell

    - include_role:
        name: apt-installer
      vars:
        package: cifs-utils

    - include_role:
        name: apt-installer
      vars:
        package: sshfs

    # gnome-backup duplicity
    - include_role:
        name: apt-installer
      vars:
        package: duplicity

    - include_role:
        name: apt-installer
      vars:
        package: cryptsetup

    - include_role:
        name: apt-installer
      vars:
        package: openvpn

    - include_role:
        name: apt-installer
      vars:
        package: virt-viewer

    - include_role:
        name: apt-installer
      vars:
        package: x11vnc

    - include_role:
        name: apt-installer
      vars:
        package: x2goclient

    - include_role:
        name: apt-installer
      vars:
        package: remmina

    - include_role:
        name: apt-installer
      vars:
        package: nodejs

    - include_role:
        name: apt-installer
      vars:
        package: exfat-fuse

    - include_role:
        name: apt-installer
      vars:
        package: lm-sensors

    - include_role:
        name: apt-installer
      vars:
        package: qtqr

    - include_role:
        name: apt-installer
      vars:
        package: vlc

    - include_role:
        name: apt-installer
      vars:
        package: nmap

    - include_role:
        name: apt-installer
      vars:
        package: wireshark

    - include_role:
        name: apt-installer
      vars:
        package: macchanger

    - include_role:
        name: apt-installer
      vars:
        package: aircrack-ng

    - include_role:
        name: apt-installer
      vars:
        package: kazam

    - name: Peek screen recorder
      apt:
        deb: https://github.com/phw/peek/releases/download/v0.8.0/peek-0.8.0-Linux.deb
      ignore_errors: yes
      become: yes
      changed_when: false

    - name: green-recorder
      snap:
        name: green-recorder
        channel: latest/edge
      become: yes
      changed_when: false
    - include_role:
        name: apt-installer
      vars:
        package: libsdl1.2debian
    - include_role:
        name: apt-installer
      vars:
        package: ffmpeg

    - name: Veracrypt ppa
      apt_repository: repo='ppa:unit193/encryption'
      become: yes
      changed_when: false
    - name: Veracrypt
      apt: update_cache=yes name=veracrypt state=latest
      become: yes
      changed_when: false

    - name: Virtualbox
      apt: update_cache=no name=virtualbox state=latest
      become: yes
      changed_when: false

    - name: kvm - qemu-kvm
      apt: update_cache=no name=qemu-kvm state=latest
      become: yes
      changed_when: false
    - name: kvm - libvirt-clients
      apt: update_cache=no name=libvirt-clients state=latest
      become: yes
      changed_when: false
    - name: kvm - libvirt-daemon-system
      apt: update_cache=no name=libvirt-daemon-system state=latest
      become: yes
      changed_when: false
    - name: kvm - virtinst
      apt: update_cache=no name=virtinst state=latest
      become: yes
      changed_when: false
    - name: kvm - bridge-utils
      apt: update_cache=no name=bridge-utils state=latest
      become: yes
      changed_when: false
    - name: kvm - cpu-checker
      apt: update_cache=no name=cpu-checker state=latest
      become: yes
      changed_when: false

    # Ideally don't use root account for virt-manager
    - name: kvm - virt-manager
      apt: update_cache=no name=virt-manager state=latest
      become: yes
      changed_when: false

    - name: Vagrant
      apt:
        deb: https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
      become: yes
      changed_when: false

    - name: Discord
      apt:
        deb: https://dl.discordapp.net/apps/linux/0.0.5/discord-0.0.5.deb
      ignore_errors: yes
      become: yes
      changed_when: false
    - name: Discord
      shell: apt install -f -y
      become: yes
      changed_when: false

    - name: OBS-Studio ppa
      apt_repository: repo='ppa:obsproject/obs-studio'
      become: yes
      changed_when: false
    - name: obs-studio
      apt: update_cache=yes name=obs-studio state=latest
      become: yes
      changed_when: false

  when: DESKTOP


- include_role: name=apt-clean
