---
- hosts: all
  roles:
    - readyup
  vars:
    GUI: true
    CHROME: true

    KEEPASS: false
    CODING: false
    PHOTOGRAPHY: false
    MEDIA: false
    GAMING: false
    DESKTOP: false

    RASPBERRYPI: false
    SERVER: false
    SERVER_LITE: false

    WORK: false
    WORK_LITE: false

    TIGERVNC_PASSWORD:
