---
- hosts: all
  roles:
    - readyup
  vars:
    GUI: true
    CHROME: true
    DESKTOP: false

    RASPBERRYPI: false

    SERVER: false
    SERVER_LITE: false

    WORK: false
    WORK_LITE: false

    TIGERVNC_PASSWORD:
