---
- hosts: all
  roles:
    - readyup
  vars:
    HIDPI: false
    CONSOLE: false
    INSTALL_GNOME: false
    WORK: false
    SERVER: false
    LITE: false
    SUPERLITE: false
    RASPBERRYPI: false
    TIGERVNC_PASSWORD:
